version: "3.9"

services:
  palaapp:
    # Build the image locally on the host (Portainer will build from the repo)
    build:
      context: .
      dockerfile: Dockerfile
    # use a local image name so Portainer doesn't try to pull from GHCR
    image: palaapp:latest
    # ensure compose rebuilds the image from source instead of pulling
    pull_policy: build
    container_name: palaapp
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # Keep DB inside container at a stable absolute path
      DATABASE_URL: "file:/app/var/db/dev.db"
      OBS_HOST: "192.168.1.120" # Cambia con IP della macchina con OBS
      OBS_PORT: "4455"
      OBS_PASSWORD: "123456"
      NEXT_TELEMETRY_DISABLED: "1"
    # No bind mounts for prisma or data to avoid schema masking and permission issues
    restart: unless-stopped
