name: Build image and upload artifact

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-build:
    name: Test Next.js build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run Next build (fast failure)
        run: npm run build

  build-image:
    name: Build Docker image and upload artifact
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (load into runner)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          load: true
          tags: |
            scoreboard:main

      - name: Save image to tar
        run: docker save scoreboard:main -o scoreboard-main.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: scoreboard-image
          path: scoreboard-main.tar
